export const languageChoices = [
  { id: 'en', name: 'English', flag: '🇬🇧' },
  { id: 'fr', name: 'Français', flag: '🇫🇷' },
  { id: 'es', name: 'Español', flag: '🇪🇸' },
  { id: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { id: 'it', name: 'Italiano', flag: '🇮🇹' },
  { id: 'pt', name: 'Português', flag: '🇵🇹' },
  { id: 'nl', name: 'Nederlands', flag: '🇳🇱' },
  { id: 'ru', name: 'Русский', flag: '🇷🇺' },
  { id: 'ja', name: '日本語', flag: '🇯🇵' },
  { id: 'zh', name: '中文', flag: '🇨🇳' },
  { id: 'ko', name: '한국어', flag: '🇰🇷' },
  { id: 'ar', name: 'العربية', flag: '🇸🇦' },
];

export const modelChoices = [
  // Google models
  {
    id: 'google/gemini-2.5-flash-preview-05-20',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    apiProvider: 'openrouter',
    modalities: ['text', 'image', 'audio', 'video'],
    context: '1M',
    price: '$0.15 / $0.60',
    description: 'Fast multimodal reasoning. Best all-round input support.',
    recommended: true,
  },
  {
    id: 'google/gemini-2.5-pro-preview-05-06',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    apiProvider: 'openrouter',
    modalities: ['text', 'image', 'audio', 'video'],
    context: '1M',
    price: '$1.25 / $10.00',
    description: 'Most capable Google model. Complex reasoning and analysis.',
  },
  {
    id: 'google/gemini-2.0-flash-001',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '1M',
    price: '$0.10 / $0.40',
    description: 'Previous gen Flash. Fast and cost effective.',
  },
  // Anthropic models
  {
    id: 'anthropic/claude-sonnet-4',
    name: 'Claude Sonnet 4',
    provider: 'Anthropic',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '200K',
    price: '$3.00 / $15.00',
    description: 'Latest Sonnet. Excellent coding and reasoning.',
  },
  {
    id: 'anthropic/claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '200K',
    price: '$3.00 / $15.00',
    description: 'Top-tier coding. Strong analysis and writing.',
  },
  {
    id: 'anthropic/claude-3.5-haiku',
    name: 'Claude 3.5 Haiku',
    provider: 'Anthropic',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '200K',
    price: '$0.80 / $4.00',
    description: 'Fast and affordable. Great for quick tasks.',
  },
  // OpenAI models
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    apiProvider: 'openrouter',
    modalities: ['text', 'image', 'audio'],
    context: '128K',
    price: '$2.50 / $10.00',
    description: 'Flagship model. Multimodal with audio support.',
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '128K',
    price: '$0.15 / $0.60',
    description: 'Affordable and fast. Perfect for everyday use.',
  },
  {
    id: 'openai/o1',
    name: 'o1',
    provider: 'OpenAI',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '200K',
    price: '$15.00 / $60.00',
    description: 'Advanced reasoning. Complex problem solving.',
  },
  // Mistral models (direct API)
  {
    id: 'mistral-medium-latest',
    name: 'Mistral Medium',
    provider: 'Mistral AI',
    apiProvider: 'mistral',
    modalities: ['text', 'image'],
    context: '128K',
    price: '€2.00 / €6.00',
    description: 'European alternative. Strong reasoning, native tool-calling.',
    flag: '🇪🇺',
  },
  {
    id: 'mistral-small-latest',
    name: 'Mistral Small',
    provider: 'Mistral AI',
    apiProvider: 'mistral',
    modalities: ['text', 'image'],
    context: '128K',
    price: '€0.20 / €0.60',
    description: 'Cost-effective European model. Great for everyday tasks.',
    flag: '🇪🇺',
  },
  {
    id: 'pixtral-large-latest',
    name: 'Pixtral Large',
    provider: 'Mistral AI',
    apiProvider: 'mistral',
    modalities: ['text', 'image'],
    context: '128K',
    price: '€2.00 / €6.00',
    description: 'Vision-focused model. Best for image understanding.',
    flag: '🇪🇺',
  },
  // Meta models
  {
    id: 'meta-llama/llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '1M',
    price: '$0.20 / $0.60',
    description: 'Latest Llama. Open-weight with strong performance.',
  },
  {
    id: 'meta-llama/llama-3.3-70b-instruct',
    name: 'Llama 3.3 70B',
    provider: 'Meta',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '128K',
    price: '$0.10 / $0.30',
    description: 'Efficient open model. Great value for performance.',
  },
  // DeepSeek
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '64K',
    price: '$0.55 / $2.19',
    description: 'Advanced reasoning model. Transparent chain-of-thought.',
  },
  {
    id: 'deepseek/deepseek-chat-v3-0324',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    apiProvider: 'openrouter',
    modalities: ['text', 'image'],
    context: '64K',
    price: '$0.14 / $0.28',
    description: 'Very affordable. Strong general capabilities.',
  },
  // Qwen
  {
    id: 'qwen/qwen-2.5-vl-72b-instruct',
    name: 'Qwen 2.5 VL 72B',
    provider: 'Qwen',
    apiProvider: 'openrouter',
    modalities: ['text', 'image', 'video'],
    context: '128K',
    price: '$0.40 / $0.40',
    description: 'Vision-language model. Video understanding support.',
  },
];

export const modalityIcons: Record<string, { icon: string; color: string }> = {
  text: { icon: 'lucide:type', color: 'text-gumm-muted' },
  image: { icon: 'lucide:image', color: 'text-sky-400' },
  audio: { icon: 'lucide:mic', color: 'text-amber-400' },
  video: { icon: 'lucide:video', color: 'text-rose-400' },
};
