#!/usr/bin/env python3
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_FILE = os.path.join(SCRIPT_DIR, "setup-server.sh")
SRC_FILE = os.path.join(SCRIPT_DIR, "src", "setup-server.sh")

LIB_FILES = [
    "lib/utils.sh",
    "lib/system.sh",
    "lib/setup.sh",
    "lib/install.sh",
    "lib/config.sh",
    "lib/network.sh",
    "lib/docker.sh",
    "lib/service.sh"
]

header = """#!/bin/bash
# =============================================================================
# COMPILED INSTALLER SCRIPT - DO NOT EDIT THIS FILE DIRECTLY!
# =============================================================================
# This file is auto-generated by scripts/build.sh.
# Please edit the files in scripts/src/ and scripts/lib/ instead.
"""

def main():
    with open(SRC_FILE, "r") as f:
        src_lines = f.readlines()
    
    # Extract the top part up to the "LOAD MODULES" section
    top_lines = []
    for line in src_lines:
        if "# LOAD MODULES" in line:
            break
        if not line.startswith("#!/bin/bash"):
            top_lines.append(line)
    
    # Remove the last few lines before LOAD MODULES that are just comment bars or empty lines
    while top_lines and (top_lines[-1].strip() == "" or top_lines[-1].startswith("# ==")):
        top_lines.pop()

    # Extract the bottom part from "UNINSTALL" to the end
    bottom_lines = []
    in_bottom = False
    for line in src_lines:
        if "# UNINSTALL" in line:
            in_bottom = True
        if in_bottom:
            bottom_lines.append(line)

    with open(OUT_FILE, "w") as out:
        out.write(header)
        out.writelines(top_lines)
        out.write("\n\n# =============================================================================\n")
        out.write("# INLINED MODULES (from scripts/lib/)\n")
        out.write("# =============================================================================\n\n")

        for lib in LIB_FILES:
            lib_path = os.path.join(SCRIPT_DIR, lib)
            out.write(f"# --- INLINED: {lib} ---\n")
            with open(lib_path, "r") as lf:
                for line in lf:
                    if not line.startswith("#!/bin/bash"):
                        out.write(line)
            out.write("\n")

        # add a separator before bottom
        out.write("\n")
        out.write("# =============================================================================\n")
        out.writelines(bottom_lines)

    os.chmod(OUT_FILE, 0o755)
    print("✅ scripts/setup-server.sh compiled successfully!")

if __name__ == "__main__":
    main()
