#!/bin/bash
# =============================================================================
# COMPILED INSTALLER SCRIPT - DO NOT EDIT THIS FILE DIRECTLY!
# =============================================================================
# This file is auto-generated by scripts/build.sh.
# Please edit the files in scripts/src/ and scripts/lib/ instead.
# =============================================================================
# Gumm — Complete VPS Installation Script
# =============================================================================
# Installs and configures Gumm from scratch on a fresh VPS.
# Supports: Ubuntu 20.04+, Debian 11+, CentOS 8+, RHEL 8+, Amazon Linux 2
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/gumm-ai/gumm/main/scripts/setup-server.sh | bash
#   # or locally:
#   sudo bash scripts/setup-server.sh
#
# Options:
#   --uninstall   Remove Gumm and all data
#   --version     Show installer version
#   --help        Show usage
# =============================================================================

# Installer version — increment this when making significant changes
INSTALLER_VERSION="1.0.1"
INSTALLER_DATE="2026-03-07"

# Store current version before potentially sourcing old config
CURRENT_INSTALLER_VERSION="$INSTALLER_VERSION"
CURRENT_INSTALLER_DATE="$INSTALLER_DATE"

# Will be set to "true" if user wants fresh install
FRESH_INSTALL="false"

set -e

# =============================================================================
# CONFIGURATION
# =============================================================================
INSTALL_DIR="${INSTALL_DIR:-/opt/gumm}"
REPO_URL="${REPO_URL:-https://github.com/gumm-ai/gumm.git}"
BRANCH="${BRANCH:-main}"

# Will be prompted if not set
GUMM_ADMIN_PASSWORD="${GUMM_ADMIN_PASSWORD:-}"
GUMM_PORT="${GUMM_PORT:-3000}"
REDIS_PORT="${REDIS_PORT:-6379}"
TAILSCALE_AUTHKEY="${TAILSCALE_AUTHKEY:-}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"

# Tailscale Funnel (set during config)
USE_TAILSCALE_FUNNEL="${USE_TAILSCALE_FUNNEL:-false}"
TAILSCALE_FUNNEL_DOMAIN=""


# =============================================================================
# INLINED MODULES (from scripts/lib/)
# =============================================================================

# --- INLINED: lib/utils.sh ---

# =============================================================================
# COLORS AND HELPERS
# =============================================================================
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }
log_step()    { echo -e "\n${CYAN}${BOLD}==> $1${NC}"; }

# Check if a TCP port is already in use
port_in_use() {
    local port="$1"
    if command -v ss &>/dev/null; then
        ss -tlnH "sport = :${port}" 2>/dev/null | grep -q "${port}"
    elif command -v netstat &>/dev/null; then
        netstat -tlnp 2>/dev/null | grep -q ":${port} "
    else
        # Fallback: try to bind
        (echo >/dev/tcp/127.0.0.1/"${port}") 2>/dev/null && return 0 || return 1
    fi
}

# --- INLINED: lib/system.sh ---

# =============================================================================
# PREFLIGHT CHECKS
# =============================================================================
preflight_checks() {
    log_step "Running preflight checks..."

    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (sudo)"
        exit 1
    fi

    # Check for existing installation and compare versions
    if [[ -f /etc/gumm/config ]]; then
        # Source config to get existing version (will overwrite INSTALLER_VERSION)
        source /etc/gumm/config
        EXISTING_VERSION="${INSTALLER_VERSION:-unknown}"
        # Restore current script version after sourcing
        INSTALLER_VERSION="$CURRENT_INSTALLER_VERSION"
        INSTALLER_DATE="$CURRENT_INSTALLER_DATE"
        
        if [[ "$EXISTING_VERSION" != "unknown" ]]; then
            log_info "Existing installation detected: v${EXISTING_VERSION}"
            if [[ "$EXISTING_VERSION" == "$CURRENT_INSTALLER_VERSION" ]]; then
                log_info "Already at latest installer version (v${CURRENT_INSTALLER_VERSION})"
            else
                log_warn "Installer version changed: v${EXISTING_VERSION} → v${CURRENT_INSTALLER_VERSION}"
            fi
            echo ""
            echo -e "  ${BOLD}1)${NC} Upgrade/reinstall (keeps data)"
            echo -e "  ${BOLD}2)${NC} Fresh install (deletes all data)"
            echo -e "  ${BOLD}3)${NC} Cancel"
            echo ""
            read -p "Choose option [1]: " INSTALL_CHOICE </dev/tty
            INSTALL_CHOICE="${INSTALL_CHOICE:-1}"
            
            case "$INSTALL_CHOICE" in
                1) log_info "Proceeding with upgrade..." ;;
                2) 
                    log_warn "This will delete ALL existing Gumm data!"
                    read -p "Are you sure? (yes/N): " CONFIRM </dev/tty
                    if [[ "$CONFIRM" != "yes" ]]; then
                        log_info "Cancelled"
                        exit 0
                    fi
                    FRESH_INSTALL="true"
                    ;;
                *) log_info "Cancelled"; exit 0 ;;
            esac
        fi
    fi

    # Check minimum RAM (1GB recommended)
    TOTAL_RAM=$(free -m | awk '/^Mem:/{print $2}')
    if [[ $TOTAL_RAM -lt 900 ]]; then
        log_warn "System has less than 1GB RAM. Gumm may run slowly."
        read -p "Continue anyway? (y/N): " CONTINUE </dev/tty
        if [[ ! $CONTINUE =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi

    # Check available disk space (5GB minimum)
    AVAILABLE_DISK=$(df -BG / | awk 'NR==2 {print $4}' | tr -d 'G')
    if [[ $AVAILABLE_DISK -lt 5 ]]; then
        log_warn "Less than 5GB disk space available."
        read -p "Continue anyway? (y/N): " CONTINUE </dev/tty
        if [[ ! $CONTINUE =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi

    log_success "Preflight checks passed (RAM: ${TOTAL_RAM}MB, Disk: ${AVAILABLE_DISK}GB free)"
}

# =============================================================================
# DETECT OS
# =============================================================================
detect_os() {
    log_step "Detecting operating system..."

    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        OS=$ID
        VERSION=$VERSION_ID
    elif [[ -f /etc/redhat-release ]]; then
        OS="centos"
        VERSION=$(grep -oE '[0-9]+' /etc/redhat-release | head -1)
    else
        log_error "Unable to detect operating system"
        exit 1
    fi

    log_info "Detected: $OS $VERSION"

    case $OS in
        ubuntu|debian)
            PKG_MANAGER="apt-get"
            PKG_UPDATE="apt-get update -qq"
            PKG_INSTALL="apt-get install -y -qq"
            ;;
        centos|rhel|fedora|rocky|almalinux)
            PKG_MANAGER="dnf"
            PKG_UPDATE="dnf check-update || true"
            PKG_INSTALL="dnf install -y -q"
            ;;
        amzn)
            PKG_MANAGER="yum"
            PKG_UPDATE="yum check-update || true"
            PKG_INSTALL="yum install -y -q"
            ;;
        *)
            log_error "Unsupported operating system: $OS"
            exit 1
            ;;
    esac

    log_success "Package manager: $PKG_MANAGER"
}

# =============================================================================
# ENABLE TUN DEVICE (Required for Tailscale in Docker)
# =============================================================================
ensure_tun_device() {
    log_step "Ensuring TUN device is available..."

    if [[ ! -c /dev/net/tun ]]; then
        log_info "Creating /dev/net/tun..."
        mkdir -p /dev/net
        mknod /dev/net/tun c 10 200
        chmod 666 /dev/net/tun
        log_success "TUN device created"
    else
        log_success "TUN device already exists"
    fi

    # Persist across reboots
    if ! grep -q '/dev/net/tun' /etc/modules-load.d/tun.conf 2>/dev/null; then
        echo "tun" > /etc/modules-load.d/tun.conf
        log_info "TUN module will load on boot"
    fi
}

# --- INLINED: lib/setup.sh ---

# =============================================================================
# CLONE OR UPDATE REPOSITORY
# =============================================================================
setup_repository() {
    log_step "Setting up Gumm repository..."

    # Configure git to use gh CLI for authentication if available
    if command -v gh &>/dev/null && gh auth status &>/dev/null; then
        log_info "Configuring Git to use GitHub CLI for authentication..."
        gh auth setup-git
    fi

    if [[ -d "$INSTALL_DIR/.git" ]]; then
        log_info "Repository exists. Pulling latest..."
        cd "$INSTALL_DIR"
        git fetch origin
        git checkout "$BRANCH"
        git pull origin "$BRANCH"
    elif [[ -d "$INSTALL_DIR" ]] && [[ -f "$INSTALL_DIR/docker-compose.yml" ]]; then
        log_info "Installation directory already contains Gumm"
        cd "$INSTALL_DIR"
    else
        log_info "Cloning repository..."
        mkdir -p "$(dirname "$INSTALL_DIR")"
        # For private repos, use gh CLI if available for auth
        if command -v gh &>/dev/null && gh auth status &>/dev/null; then
            gh repo clone "$REPO_URL" "$INSTALL_DIR" -- --branch "$BRANCH"
        else
            git clone --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
        fi
        cd "$INSTALL_DIR"
    fi

    # Ensure module directories exist
    mkdir -p "$INSTALL_DIR/modules/user"
    mkdir -p "$INSTALL_DIR/brain"

    log_success "Repository ready at $INSTALL_DIR"
}

# --- INLINED: lib/install.sh ---

# =============================================================================
# INSTALL SYSTEM DEPENDENCIES
# =============================================================================
install_dependencies() {
    log_step "Installing system dependencies..."

    $PKG_UPDATE

    case $OS in
        ubuntu|debian)
            $PKG_INSTALL curl wget git openssl ca-certificates gnupg lsb-release make
            ;;
        centos|rhel|fedora|rocky|almalinux)
            $PKG_INSTALL curl wget git openssl ca-certificates make
            ;;
        amzn)
            $PKG_INSTALL curl wget git openssl make
            ;;
    esac

    log_success "System dependencies installed"
}

# =============================================================================
# INSTALL DOCKER
# =============================================================================
install_docker() {
    log_step "Checking Docker installation..."

    if command -v docker &> /dev/null; then
        DOCKER_VERSION=$(docker --version | awk '{print $3}' | tr -d ',')
        log_info "Docker already installed: $DOCKER_VERSION"

        if docker compose version &> /dev/null; then
            log_info "Docker Compose (plugin) available"
            return 0
        elif command -v docker-compose &> /dev/null; then
            log_info "Docker Compose (standalone) available"
            return 0
        fi
    fi

    log_info "Installing Docker..."

    case $OS in
        ubuntu|debian)
            apt-get remove -y docker docker-engine docker.io containerd runc 2>/dev/null || true

            install -m 0755 -d /etc/apt/keyrings
            curl -fsSL "https://download.docker.com/linux/$OS/gpg" | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            chmod a+r /etc/apt/keyrings/docker.gpg

            echo \
              "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/$OS \
              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
              tee /etc/apt/sources.list.d/docker.list > /dev/null

            apt-get update -qq
            apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            ;;

        centos|rhel|rocky|almalinux)
            dnf remove -y docker docker-client docker-client-latest docker-common docker-latest \
                docker-latest-logrotate docker-logrotate docker-engine 2>/dev/null || true

            dnf install -y dnf-plugins-core
            dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            ;;

        fedora)
            dnf remove -y docker docker-client docker-client-latest docker-common docker-latest \
                docker-latest-logrotate docker-logrotate docker-selinux docker-engine-selinux docker-engine 2>/dev/null || true

            dnf install -y dnf-plugins-core
            dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
            dnf install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            ;;

        amzn)
            yum remove -y docker docker-client docker-client-latest docker-common docker-latest \
                docker-latest-logrotate docker-logrotate docker-engine 2>/dev/null || true

            amazon-linux-extras install docker -y 2>/dev/null || yum install -y docker
            ;;
    esac

    systemctl start docker
    systemctl enable docker

    docker --version
    docker compose version 2>/dev/null || docker-compose --version

    log_success "Docker installed successfully"
}

# =============================================================================
# INSTALL TAILSCALE
# =============================================================================
install_tailscale() {
    log_step "Checking Tailscale installation..."

    if command -v tailscale &> /dev/null; then
        TS_VERSION=$(tailscale version 2>/dev/null | head -1)
        log_info "Tailscale already installed: $TS_VERSION"
        return 0
    fi

    log_info "Installing Tailscale..."

    # Tailscale is optional — don't abort the whole install if it fails
    if curl -fsSL https://tailscale.com/install.sh | sh; then
        systemctl enable tailscaled
        systemctl start tailscaled
        log_success "Tailscale installed"
    else
        log_warn "Tailscale installation failed (this is optional, continuing...)"
        log_info "You can install Tailscale manually later: https://tailscale.com/download"
        return 0
    fi
}

# =============================================================================
# INSTALL NETBIRD
# =============================================================================
install_netbird() {
    log_step "Installing NetBird..."

    # Check if NetBird is ACTUALLY installed and working
    # command -v can pass even if binary is broken/missing
    if command -v netbird &> /dev/null; then
        NB_VERSION=$(netbird version 2>/dev/null | head -1)
        # Verify the binary actually works (non-empty version output)
        if [[ -n "$NB_VERSION" ]] && [[ -x "$(command -v netbird)" ]]; then
            log_info "NetBird already installed: $NB_VERSION"
            return 0
        else
            log_warn "NetBird binary found but not working, reinstalling..."
            # Clean up broken installation
            apt-get remove -y netbird 2>/dev/null || true
            rm -f /usr/bin/netbird /usr/local/bin/netbird 2>/dev/null || true
            hash -r  # Clear shell command cache
        fi
    fi

    log_info "Downloading NetBird..."

    # Use the official install script
    if curl -fsSL https://pkgs.netbird.io/install.sh | sh; then
        hash -r  # Clear shell command cache
        # Verify installation actually works (not just in PATH)
        if netbird version &>/dev/null; then
            # DON'T start the service here - it needs config first
            # The service will be started after 'netbird up' in configure_vpn_host()
            systemctl stop netbird 2>/dev/null || true
            NB_VERSION=$(netbird version 2>/dev/null | head -1)
            log_success "NetBird installed: $NB_VERSION"
            return 0
        fi
    fi

    # Fallback: manual binary installation if official script failed
    log_warn "Official install script failed, trying manual installation..."
    
    ARCH=$(uname -m)
    case $ARCH in
        x86_64)  NB_ARCH="linux_amd64" ;;
        aarch64) NB_ARCH="linux_arm64" ;;
        armv7l)  NB_ARCH="linux_armv6" ;;
        *)       NB_ARCH="linux_amd64" ;;
    esac

    # Get latest release version
    NB_LATEST=$(curl -fsSL https://api.github.com/repos/netbirdio/netbird/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
    if [[ -z "$NB_LATEST" ]]; then
        NB_LATEST="0.66.2"  # Fallback version
    fi

    log_info "Downloading NetBird v$NB_LATEST for $NB_ARCH..."
    
    cd /tmp
    if curl -fsSL "https://github.com/netbirdio/netbird/releases/download/v${NB_LATEST}/netbird_${NB_LATEST}_${NB_ARCH}.tar.gz" -o netbird.tar.gz; then
        tar -xzf netbird.tar.gz
        mv netbird /usr/local/bin/netbird
        chmod +x /usr/local/bin/netbird
        # Also create symlink in /usr/bin for compatibility (some systems expect it there)
        ln -sf /usr/local/bin/netbird /usr/bin/netbird
        rm -f netbird.tar.gz
        hash -r  # Clear shell command cache
        
        # Create systemd service (but don't start it yet)
        cat > /etc/systemd/system/netbird.service << 'EOF'
[Unit]
Description=NetBird Service
After=network.target

[Service]
Type=simple
ExecStart=/usr/local/bin/netbird service run
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

        systemctl daemon-reload
        # DON'T enable/start here - wait for configure_vpn_host()
        
        # Verify installation actually works
        if /usr/local/bin/netbird version &>/dev/null; then
            NB_VERSION=$(/usr/local/bin/netbird version 2>/dev/null | head -1)
            log_success "NetBird installed manually: $NB_VERSION"
            return 0
        fi
    fi

    log_warn "NetBird installation failed. You can install it manually later:"
    log_info "  curl -fsSL https://pkgs.netbird.io/install.sh | sh"
    return 0
}

# =============================================================================
# INSTALL GO
# =============================================================================
install_go() {
    log_step "Checking Go installation..."

    if command -v go &> /dev/null; then
        GO_VERSION=$(go version | awk '{print $3}')
        log_info "Go already installed: $GO_VERSION"
        return 0
    fi

    log_info "Installing Go..."

    # Prefer the official tarball for a recent version (package managers often ship old Go)
    local go_version="1.23.6"
    local arch
    case "$(uname -m)" in
        x86_64|amd64)  arch="amd64" ;;
        aarch64|arm64) arch="arm64" ;;
        *)             arch="amd64" ;;
    esac

    local tarball="go${go_version}.linux-${arch}.tar.gz"
    local url="https://go.dev/dl/${tarball}"

    log_info "Downloading Go ${go_version} (${arch})..."
    curl -fsSL -o "/tmp/${tarball}" "$url"
    rm -rf /usr/local/go
    tar -C /usr/local -xzf "/tmp/${tarball}"
    rm -f "/tmp/${tarball}"

    # Make Go available system-wide
    if ! grep -q '/usr/local/go/bin' /etc/profile.d/go.sh 2>/dev/null; then
        echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/go.sh
        chmod +x /etc/profile.d/go.sh
    fi
    export PATH=$PATH:/usr/local/go/bin

    if command -v go &> /dev/null; then
        log_success "Go installed: $(go version | awk '{print $3}')"
    else
        log_warn "Go installation failed. CLI will not be built."
    fi
}

# =============================================================================
# INSTALL GUMM CLI
# =============================================================================
install_cli() {
    log_step "Installing Gumm CLI..."

    # Detect platform
    local os arch
    case "$(uname -s)" in
        Linux*)  os="linux" ;;
        Darwin*) os="darwin" ;;
        *)       log_warn "Unsupported OS for CLI: $(uname -s)"; return 0 ;;
    esac
    case "$(uname -m)" in
        x86_64|amd64)  arch="amd64" ;;
        aarch64|arm64) arch="arm64" ;;
        *)             log_warn "Unsupported arch for CLI: $(uname -m)"; return 0 ;;
    esac

    local platform="${os}-${arch}"
    local repo_path
    repo_path=$(echo "$REPO_URL" | sed 's|https://github.com/||;s|\.git$||')

    # Strategy 1: Download pre-built binary from GitHub releases
    local version
    version=$(curl -fsSL "https://api.github.com/repos/${repo_path}/releases/latest" 2>/dev/null \
        | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"//;s/".*//' || echo "")

    if [[ -n "$version" ]]; then
        local asset="gumm-${platform}"
        local url="https://github.com/${repo_path}/releases/download/${version}/${asset}"
        log_info "Downloading CLI ${version} (${platform})..."

        local tmp
        tmp=$(mktemp)
        if curl -fsSL -o "$tmp" "$url" 2>/dev/null; then
            chmod +x "$tmp"
            mv "$tmp" "/usr/local/bin/gumm"
            log_success "CLI ${version} installed to /usr/local/bin/gumm"

            if command -v gumm &>/dev/null; then
                log_success "CLI ready: $(gumm --version 2>/dev/null || echo 'installed')"
            fi
            return 0
        fi
        rm -f "$tmp"
        log_info "No pre-built binary for ${platform}, falling back to source build..."
    fi

    # Strategy 2: Build from source using Make
    if [[ ! -d "$INSTALL_DIR/cli" ]]; then
        log_warn "CLI source not found. Install later with:"
        log_warn "  curl -fsSL https://raw.githubusercontent.com/${repo_path}/main/scripts/install.sh | bash"
        return 0
    fi

    if ! command -v go &>/dev/null; then
        log_warn "Go is not available. CLI not built."
        log_warn "  Install Go and run: cd ${INSTALL_DIR} && make build && make install"
        return 0
    fi

    log_info "Building CLI from source (make build)..."
    cd "$INSTALL_DIR"

    if command -v make &>/dev/null; then
        make build
        # Install to /usr/local/bin (more reliable on servers than GOPATH)
        cp bin/gumm /usr/local/bin/gumm
        chmod +x /usr/local/bin/gumm
        log_success "CLI built and installed to /usr/local/bin/gumm"
    else
        # Fallback without make
        cd "$INSTALL_DIR/cli"
        go build -ldflags "-s -w" -o /usr/local/bin/gumm .
        cd "$INSTALL_DIR"
        log_success "CLI built and installed to /usr/local/bin/gumm"
    fi

    if command -v gumm &>/dev/null; then
        log_success "CLI ready: $(gumm --version 2>/dev/null || echo 'installed')"
    fi
}

# --- INLINED: lib/config.sh ---

# =============================================================================
# PROMPT FOR CONFIGURATION
# =============================================================================
prompt_configuration() {
    log_step "Configuration"

    echo ""
    echo -e "${BOLD}Please provide the following information:${NC}"
    echo ""

    # Admin password
    if [[ -z "$GUMM_ADMIN_PASSWORD" ]]; then
        while true; do
            read -sp "Admin password for Gumm dashboard: " GUMM_ADMIN_PASSWORD </dev/tty
            echo ""
            if [[ ${#GUMM_ADMIN_PASSWORD} -lt 8 ]]; then
                log_error "Password must be at least 8 characters"
                continue
            fi
            read -sp "Confirm password: " CONFIRM_PASSWORD </dev/tty
            echo ""
            if [[ "$GUMM_ADMIN_PASSWORD" != "$CONFIRM_PASSWORD" ]]; then
                log_error "Passwords do not match"
                continue
            fi
            break
        done
    fi

    # Port
    read -p "Gumm port [${GUMM_PORT}]: " INPUT_PORT </dev/tty
    GUMM_PORT="${INPUT_PORT:-$GUMM_PORT}"

    # Check if port is available, auto-find next free one if not
    while port_in_use "$GUMM_PORT"; do
        log_warn "Port ${GUMM_PORT} is already in use."
        NEXT_PORT=$((GUMM_PORT + 1))
        # Find the next free port
        while port_in_use "$NEXT_PORT"; do
            NEXT_PORT=$((NEXT_PORT + 1))
        done
        read -p "Use port ${NEXT_PORT} instead? (Y/n): " USE_NEXT </dev/tty
        if [[ "$USE_NEXT" =~ ^[Nn]$ ]]; then
            read -p "Enter a different port: " GUMM_PORT </dev/tty
        else
            GUMM_PORT="$NEXT_PORT"
        fi
    done
    log_success "Port ${GUMM_PORT} is available"

    # Also check Redis port
    while port_in_use "$REDIS_PORT"; do
        log_warn "Redis port ${REDIS_PORT} is already in use."
        NEXT_REDIS=$((REDIS_PORT + 1))
        while port_in_use "$NEXT_REDIS"; do
            NEXT_REDIS=$((NEXT_REDIS + 1))
        done
        read -p "Use Redis port ${NEXT_REDIS} instead? (Y/n): " USE_NEXT_REDIS </dev/tty
        if [[ "$USE_NEXT_REDIS" =~ ^[Nn]$ ]]; then
            read -p "Enter a different Redis port: " REDIS_PORT </dev/tty
        else
            REDIS_PORT="$NEXT_REDIS"
        fi
    done

    # Timezone
    CURRENT_TZ=$(timedatectl show --property=Timezone --value 2>/dev/null || echo "Europe/Paris")
    read -p "Timezone [${CURRENT_TZ}]: " INPUT_TZ </dev/tty
    TZ="${INPUT_TZ:-$CURRENT_TZ}"

    # VPN Selection (optional — can also be configured later from the dashboard)
    echo ""
    echo -e "${BOLD}VPN Mesh Networking Setup${NC}"
    echo -e "${DIM}VPN enables secure mesh networking between your Gumm instance"
    echo -e "and remote CLI agents. You can also configure this later from the dashboard.${NC}"
    echo ""
    echo -e "Choose your VPN provider:"
    echo -e "  ${BOLD}1)${NC} Tailscale   ${DIM}(Toronto, Canada)${NC}"
    echo -e "  ${BOLD}2)${NC} NetBird     ${DIM}(Berlin, Germany — EU alternative)${NC}"
    echo -e "  ${BOLD}3)${NC} Skip for now"
    echo ""
    read -p "Select VPN provider [3]: " VPN_CHOICE </dev/tty
    VPN_CHOICE="${VPN_CHOICE:-3}"

    VPN_PROVIDER="none"
    VPN_AUTHKEY=""

    case "$VPN_CHOICE" in
        1)
            VPN_PROVIDER="tailscale"
            echo ""
            echo -e "${CYAN}To get your Tailscale auth key:${NC}"
            echo -e "  1. Create an account at: ${BOLD}https://login.tailscale.com/start${NC}"
            echo -e "  2. Go to: ${BOLD}https://login.tailscale.com/admin/settings/keys${NC}"
            echo -e "  3. Click 'Generate auth key' and copy the key"
            echo ""
            read -p "Tailscale auth key (leave empty to skip): " VPN_AUTHKEY </dev/tty
            TAILSCALE_AUTHKEY="$VPN_AUTHKEY"
            ;;
        2)
            VPN_PROVIDER="netbird"
            echo ""
            echo -e "${CYAN}To get your NetBird setup key:${NC}"
            echo -e "  1. Create an account at: ${BOLD}https://app.netbird.io${NC}"
            echo -e "  2. Go to: ${BOLD}https://app.netbird.io/setup-keys${NC}"
            echo -e "  3. Click 'Create Setup Key' and copy the key"
            echo ""
            read -p "NetBird setup key (leave empty to skip): " VPN_AUTHKEY </dev/tty
            NETBIRD_SETUP_KEY="$VPN_AUTHKEY"
            ;;
        *)
            log_info "VPN setup skipped — you can configure it later from the dashboard"
            ;;
    esac

    # Telegram Bot (optional)
    echo ""
    echo -e "${BOLD}Telegram Bot Setup${NC}"
    echo -e "${DIM}Connect a Telegram bot to chat with Gumm from anywhere."
    echo -e "You can also configure this later from the dashboard.${NC}"
    echo ""
    echo -e "${CYAN}To create a Telegram bot:${NC}"
    echo -e "  1. Open Telegram and search for ${BOLD}@BotFather${NC}"
    echo -e "  2. Send ${BOLD}/newbot${NC} and follow the instructions"
    echo -e "  3. Copy the bot token (looks like: 123456789:ABCdefGHI...)"
    echo ""
    read -p "Telegram bot token (leave empty to skip): " TELEGRAM_BOT_TOKEN </dev/tty

    if [[ -n "$TELEGRAM_BOT_TOKEN" ]]; then
        echo ""
        echo -e "${GREEN}Bot token saved!${NC}"
        echo ""
        echo -e "${CYAN}To get your Chat ID:${NC}"
        echo -e "  1. Open Telegram and find your new bot (search for its username)"
        echo -e "  2. Send ${BOLD}/start${NC} to your bot"
        echo -e "  3. The bot will reply with your Chat ID"
        echo ""
        echo -e "${DIM}Restricting access to your Chat ID is recommended for security.${NC}"
        read -p "Your Chat ID (leave empty to allow all): " TELEGRAM_CHAT_ID </dev/tty
    fi

    # GitHub token (optional)
    echo ""
    echo -e "${DIM}A GitHub token is only needed to install modules from private repos"
    echo -e "or to avoid API rate limits.${NC}"
    read -p "GitHub personal access token (leave empty to skip): " GITHUB_TOKEN </dev/tty

    # =============================================================================
    # HTTPS SETUP (Tailscale Funnel or Caddy reverse proxy)
    # =============================================================================
    USE_CADDY_PROXY="false"
    USE_TAILSCALE_FUNNEL="false"
    CADDY_DOMAIN=""

    if [[ "$VPN_PROVIDER" == "tailscale" ]]; then
        echo ""
        echo -e "${BOLD}HTTPS Setup — Tailscale Funnel${NC}"
        echo -e "${DIM}Tailscale Funnel exposes your Gumm instance over HTTPS directly"
        echo -e "through Tailscale's edge network — no reverse proxy needed."
        echo -e "Your instance will be accessible at https://<your-machine>.ts.net${NC}"
        echo ""
        read -p "Enable Tailscale Funnel? (Y/n): " ENABLE_FUNNEL </dev/tty
        ENABLE_FUNNEL="${ENABLE_FUNNEL:-Y}"

        if [[ "$ENABLE_FUNNEL" =~ ^[Yy]$ ]]; then
            USE_TAILSCALE_FUNNEL="true"
            log_info "Tailscale Funnel will be configured after VPN connection"
        fi
    elif [[ "$VPN_PROVIDER" == "netbird" ]]; then
        echo ""
        echo -e "${BOLD}Reverse Proxy Setup (Caddy)${NC}"
        echo -e "${DIM}A reverse proxy adds HTTPS and proper IP forwarding for VPN Guard."
        echo -e "Recommended if you're using NetBird.${NC}"
        echo ""
        read -p "Enable Caddy reverse proxy? (Y/n): " ENABLE_CADDY </dev/tty
        ENABLE_CADDY="${ENABLE_CADDY:-Y}"

        if [[ "$ENABLE_CADDY" =~ ^[Yy]$ ]]; then
            USE_CADDY_PROXY="true"
            log_info "Caddy will be configured after VPN connection (domain auto-detected)"
        fi
    fi

    echo ""
    log_success "Configuration collected"
}

# =============================================================================
# CONFIGURE CADDY DOMAIN (after VPN is connected)
# =============================================================================
configure_caddy_domain() {
    if [[ "$USE_CADDY_PROXY" != "true" ]]; then
        return 0
    fi

    log_step "Configuring Caddy domain..."

    # Try to auto-detect VPN domain now that VPN is connected
    DETECTED_DOMAIN=""
    
    if [[ "$VPN_PROVIDER" == "tailscale" ]]; then
        if command -v tailscale &>/dev/null && tailscale status &>/dev/null; then
            DETECTED_DOMAIN=$(tailscale status --json 2>/dev/null | grep -o '"DNSName":"[^"]*"' | head -1 | sed 's/"DNSName":"//;s/"$//' | sed 's/\.$//')
        fi
        if [[ -z "$DETECTED_DOMAIN" ]]; then
            echo -e "${CYAN}Enter your Tailscale MagicDNS hostname:${NC}"
            echo -e "  ${DIM}(Example: gumm-server.tail12345.ts.net)${NC}"
            echo -e "  ${DIM}Find it with: tailscale status${NC}"
        fi
    elif [[ "$VPN_PROVIDER" == "netbird" ]]; then
        if command -v netbird &>/dev/null && netbird status 2>/dev/null | grep -q "Connected"; then
            DETECTED_DOMAIN=$(netbird status 2>/dev/null | grep -oP 'FQDN:\s*\K[^\s]+' | head -1)
        fi
        if [[ -z "$DETECTED_DOMAIN" ]]; then
            echo -e "${CYAN}Enter your NetBird FQDN:${NC}"
            echo -e "  ${DIM}(Example: my-server.netbird.cloud)${NC}"
            echo -e "  ${DIM}Find it with: netbird status${NC}"
        fi
    fi

    if [[ -n "$DETECTED_DOMAIN" ]]; then
        echo -e "${GREEN}Detected VPN domain: ${BOLD}${DETECTED_DOMAIN}${NC}"
        read -p "Use this domain? (Y/n): " USE_DETECTED </dev/tty
        USE_DETECTED="${USE_DETECTED:-Y}"
        if [[ "$USE_DETECTED" =~ ^[Yy]$ ]]; then
            CADDY_DOMAIN="$DETECTED_DOMAIN"
        fi
    fi

    if [[ -z "$CADDY_DOMAIN" ]]; then
        read -p "VPN domain for Caddy: " CADDY_DOMAIN </dev/tty
    fi

    if [[ -z "$CADDY_DOMAIN" ]]; then
        log_warn "No domain provided, Caddy proxy will not be enabled"
        USE_CADDY_PROXY="false"
    else
        log_success "Caddy will proxy: https://${CADDY_DOMAIN}"
        
        # Update .env file with the domain
        if [[ -f "$INSTALL_DIR/.env" ]]; then
            sed -i "s|^CADDY_DOMAIN=.*|CADDY_DOMAIN=${CADDY_DOMAIN}|" "$INSTALL_DIR/.env"
        fi
    fi
}

# =============================================================================
# GENERATE SECRETS & CREATE .env
# =============================================================================
create_env_file() {
    log_step "Generating secrets and environment file..."

    ENV_FILE="$INSTALL_DIR/.env"

    # Generate session secret (64 hex chars)
    NUXT_SESSION_PASSWORD=$(openssl rand -hex 32)
    log_info "Generated session secret"

    cat > "$ENV_FILE" << EOF
# =============================================================================
# Gumm — Environment Configuration
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Installer: v${INSTALLER_VERSION} (${INSTALLER_DATE})
# =============================================================================

# ─── Authentication ──────────────────────────────────────────────────────────
# Admin password for the web dashboard
GUMM_ADMIN_PASSWORD=${GUMM_ADMIN_PASSWORD}

# Session encryption secret (auto-generated, do not change)
NUXT_SESSION_PASSWORD=${NUXT_SESSION_PASSWORD}

# ─── Ports ───────────────────────────────────────────────────────────────────
GUMM_PORT=${GUMM_PORT}
REDIS_PORT=${REDIS_PORT}

# ─── Redis ───────────────────────────────────────────────────────────────────
# Internal Docker network URL (do not change unless you know what you're doing)
REDIS_URL=redis://redis:6379

# ─── Timezone ────────────────────────────────────────────────────────────────
TZ=${TZ}

# ─── Optional: GitHub Token ──────────────────────────────────────────────────
# Needed for installing modules from private repos
GITHUB_TOKEN=${GITHUB_TOKEN:-}

# ─── VPN Configuration ───────────────────────────────────────────────────────
# VPN provider: tailscale, netbird, or none
VPN_PROVIDER=${VPN_PROVIDER:-none}

# NetBird setup key (if using NetBird)
NB_SETUP_KEY=${NETBIRD_SETUP_KEY:-}
NB_HOSTNAME=${NB_HOSTNAME:-gumm}

# Tailscale auth key (if using Tailscale)
TS_AUTHKEY=${TAILSCALE_AUTHKEY:-}

# ─── Telegram Configuration ──────────────────────────────────────────────────
# Telegram bot token (from @BotFather)
TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}

# Allowed Telegram chat ID (leave empty to allow all)
TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID:-}

# ─── Caddy Reverse Proxy ─────────────────────────────────────────────────────
# Enable Caddy proxy with: docker compose --profile proxy up -d
# Domain for Caddy (Tailscale MagicDNS or NetBird FQDN)
CADDY_DOMAIN=${CADDY_DOMAIN:-}

# Set to restrict Caddy/Gumm to VPN IP only (e.g., 100.87.158.182)
# Leave empty to bind to all interfaces (0.0.0.0)
VPN_BIND_IP=${VPN_BIND_IP:-}

# Path to Tailscale SSL certificates (for .ts.net domains)
TAILSCALE_CERTS_PATH=/var/lib/tailscale/certs

# ─── Note ────────────────────────────────────────────────────────────────────
# OpenRouter API key is configured via the web Setup Wizard (/setup).
# Google OAuth and other integrations are also configured from the dashboard.
EOF

    chmod 600 "$ENV_FILE"

    log_success "Environment file created: $ENV_FILE"
}

# =============================================================================
# CREATE GLOBAL CONFIG FILE
# =============================================================================
create_global_config() {
    log_step "Creating global configuration..."

    mkdir -p /etc/gumm

    cat > /etc/gumm/config << EOF
# Gumm Installation Configuration
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Installer version used for this installation
INSTALLER_VERSION="${INSTALLER_VERSION}"
INSTALLER_DATE="${INSTALLER_DATE}"

INSTALL_DIR="${INSTALL_DIR}"
GUMM_PORT="${GUMM_PORT}"
REDIS_PORT="${REDIS_PORT}"
REPO_URL="${REPO_URL}"
BRANCH="${BRANCH}"
VPN_PROVIDER="${VPN_PROVIDER}"
USE_CADDY_PROXY="${USE_CADDY_PROXY}"
CADDY_DOMAIN="${CADDY_DOMAIN:-}"
EOF

    chmod 644 /etc/gumm/config

    log_success "Global config saved to /etc/gumm/config"
}

# --- INLINED: lib/network.sh ---

# =============================================================================
# CONFIGURE FIREWALL
# =============================================================================
configure_firewall() {
    log_step "Configuring firewall..."

    # UFW (Ubuntu/Debian)
    if command -v ufw &> /dev/null; then
        log_info "Configuring UFW..."
        ufw --force enable
        ufw allow ssh
        ufw allow "${GUMM_PORT}/tcp"
        # Allow Tailscale UDP
        ufw allow 41641/udp
        # Allow NetBird UDP
        ufw allow 51820/udp
        ufw reload
        log_success "UFW configured (ports: SSH, ${GUMM_PORT}/tcp, 41641/udp, 51820/udp)"
        return 0
    fi

    # firewalld (CentOS/RHEL)
    if command -v firewall-cmd &> /dev/null && systemctl is-active firewalld &> /dev/null; then
        log_info "Configuring firewalld..."
        firewall-cmd --permanent --add-service=ssh
        firewall-cmd --permanent --add-port="${GUMM_PORT}/tcp"
        firewall-cmd --permanent --add-port=41641/udp
        firewall-cmd --permanent --add-port=51820/udp
        firewall-cmd --reload
        log_success "firewalld configured"
        return 0
    fi

    log_warn "No active firewall detected. Consider configuring one manually."
}

# =============================================================================
# CONFIGURE VPN ON HOST (optional — Tailscale or NetBird)
# =============================================================================
# VPN (Tailscale/NetBird) MUST run on the host, not in Docker.
# This avoids conflicts and simplifies networking.
# When VPN is on the host:
#   - Traffic arrives via VPN IP on the host
#   - Host forwards to Docker container via Docker network
#   - Container sees traffic from Docker gateway (172.x.x.x)
#   - vpn-guard middleware allows Docker internal IPs when VPN mode is set
configure_vpn_host() {
    if [[ "$VPN_PROVIDER" == "tailscale" ]] && [[ -n "$TAILSCALE_AUTHKEY" ]]; then
        log_step "Configuring Tailscale on host..."

        if ! command -v tailscale &> /dev/null; then
            log_warn "Tailscale binary not found on host."
            log_info "Install it manually: curl -fsSL https://tailscale.com/install.sh | sh"
            return 0
        fi

        # Check if already connected
        if tailscale status &>/dev/null; then
            log_info "Tailscale is already connected on host"
            return 0
        fi

        tailscale up --authkey="$TAILSCALE_AUTHKEY" --hostname="gumm-server"
        log_success "Tailscale connected on host"

    elif [[ "$VPN_PROVIDER" == "netbird" ]] && [[ -n "$NETBIRD_SETUP_KEY" ]]; then
        log_step "Configuring NetBird on host..."

        # Verify NetBird binary actually exists and works
        if ! command -v netbird &> /dev/null || ! netbird version &>/dev/null; then
            log_warn "NetBird binary not found or not working."
            log_info "Attempting to install NetBird..."
            if ! install_netbird; then
                log_warn "NetBird installation failed."
                log_info "Install it manually: curl -fsSL https://pkgs.netbird.io/install.sh | sh"
                return 0
            fi
        fi

        # Check if already connected
        if netbird status 2>/dev/null | grep -q "Connected"; then
            log_info "NetBird is already connected on host"
            return 0
        fi

        # Stop any existing service first
        systemctl stop netbird 2>/dev/null || true

        # Install the service (creates config dir structure)
        netbird service install 2>/dev/null || true

        # Start the service - this creates the socket that netbird up needs
        netbird service start 2>/dev/null || systemctl start netbird 2>/dev/null || true
        
        # Wait a moment for the socket to be created
        sleep 2

        # Connect with setup key (this creates the config)
        if netbird up --setup-key "$NETBIRD_SETUP_KEY"; then
            log_success "NetBird connected on host"
            # Now enable the service for persistence
            systemctl enable netbird 2>/dev/null || true
        else
            log_warn "NetBird connection failed. You can try manually: netbird up --setup-key YOUR_KEY"
        fi
    fi
}

# =============================================================================
# CONFIGURE CADDY SSL CERTIFICATES
# =============================================================================
configure_caddy_ssl() {
    if [[ "$USE_CADDY_PROXY" != "true" ]] || [[ -z "$CADDY_DOMAIN" ]]; then
        return 0
    fi

    log_step "Configuring Caddy SSL certificates..."

    # Create certs directory
    mkdir -p /var/lib/tailscale/certs

    if [[ "$VPN_PROVIDER" == "tailscale" ]]; then
        # For Tailscale: generate certs with `tailscale cert`
        log_info "Generating Tailscale SSL certificate for ${CADDY_DOMAIN}..."
        
        if tailscale cert --cert-file="/var/lib/tailscale/certs/${CADDY_DOMAIN}.crt" \
                         --key-file="/var/lib/tailscale/certs/${CADDY_DOMAIN}.key" \
                         "$CADDY_DOMAIN" 2>/dev/null; then
            log_success "Tailscale certificate generated"
            
            # Generate Caddyfile with explicit TLS
            cat > "$INSTALL_DIR/scripts/Caddyfile" << EOF
# Gumm Reverse Proxy - Tailscale SSL
# Auto-generated by setup-server.sh

${CADDY_DOMAIN} {
    tls /etc/caddy/tailscale-certs/${CADDY_DOMAIN}.crt /etc/caddy/tailscale-certs/${CADDY_DOMAIN}.key
    
    reverse_proxy gumm:3000 {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up Host {host}
    }
}

:8080 {
    respond /health "OK" 200
}
EOF
        else
            log_warn "Could not generate Tailscale certificate. Using internal TLS."
            # Fallback to internal CA
            cat > "$INSTALL_DIR/scripts/Caddyfile" << EOF
# Gumm Reverse Proxy - Internal TLS (self-signed)
# Auto-generated by setup-server.sh

${CADDY_DOMAIN} {
    tls internal
    
    reverse_proxy gumm:3000 {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up Host {host}
    }
}

:8080 {
    respond /health "OK" 200
}
EOF
        fi

    elif [[ "$VPN_PROVIDER" == "netbird" ]]; then
        # Check if domain is VPN-only (*.netbird.cloud) - can't use Let's Encrypt
        if [[ "$CADDY_DOMAIN" == *.netbird.cloud ]]; then
            log_info "Configuring internal TLS for ${CADDY_DOMAIN} (VPN-only domain)..."
            
            cat > "$INSTALL_DIR/scripts/Caddyfile" << EOF
# Gumm Reverse Proxy - Internal TLS (VPN-only domain)
# Auto-generated by setup-server.sh
# Note: *.netbird.cloud domains are VPN-only, so Let's Encrypt cannot validate them.
# Using Caddy's internal CA instead (you'll see a browser warning on first visit).

${CADDY_DOMAIN} {
    tls internal
    
    reverse_proxy gumm:3000 {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up Host {host}
    }
}

:8080 {
    respond /health "OK" 200
}
EOF
            log_success "Caddy configured with internal TLS (self-signed)"
        else
            # Public domain - use Let's Encrypt
            log_info "Configuring Let's Encrypt for ${CADDY_DOMAIN}..."
            
            cat > "$INSTALL_DIR/scripts/Caddyfile" << EOF
# Gumm Reverse Proxy - Let's Encrypt SSL
# Auto-generated by setup-server.sh

${CADDY_DOMAIN} {
    # Let's Encrypt will auto-generate certificate
    
    reverse_proxy gumm:3000 {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up Host {host}
    }
}

:8080 {
    respond /health "OK" 200
}
EOF
            log_success "Caddy configured for Let's Encrypt"
        fi
    fi
}

# =============================================================================
# CONFIGURE TAILSCALE FUNNEL
# =============================================================================
# Tailscale Funnel exposes a local port over HTTPS via Tailscale's edge network.
# No reverse proxy (Caddy) is needed when Funnel is enabled.
# Docs: https://tailscale.com/docs/features/tailscale-funnel
configure_tailscale_funnel() {
    if [[ "$USE_TAILSCALE_FUNNEL" != "true" ]]; then
        return 0
    fi

    log_step "Configuring Tailscale Funnel..."

    if ! command -v tailscale &> /dev/null; then
        log_warn "Tailscale binary not found, cannot enable Funnel"
        return 1
    fi

    # Ensure Tailscale is connected
    if ! tailscale status &>/dev/null; then
        log_warn "Tailscale is not connected, cannot enable Funnel"
        return 1
    fi

    # Enable HTTPS on the Tailscale node (required for Funnel)
    tailscale set --webclient=false 2>/dev/null || true

    # Start Funnel in background mode, forwarding to the Gumm port
    FUNNEL_OUTPUT=$(tailscale funnel --bg "${GUMM_PORT}" 2>&1)
    if [[ $? -eq 0 ]]; then
        # Detect the Funnel URL — first try parsing the funnel command output
        FUNNEL_DOMAIN=$(echo "$FUNNEL_OUTPUT" | grep -oP 'https://\K[^/]+\.ts\.net' | head -1)
        # Fallback: detect from tailscale status --json
        if [[ -z "$FUNNEL_DOMAIN" ]]; then
            FUNNEL_DOMAIN=$(tailscale status --json 2>/dev/null | grep -o '"DNSName":"[^"]*"' | head -1 | sed 's/"DNSName":"//;s/"$//' | sed 's/\.$//')
        fi
        if [[ -n "$FUNNEL_DOMAIN" ]]; then
            log_success "Tailscale Funnel active: https://${FUNNEL_DOMAIN}"
            TAILSCALE_FUNNEL_DOMAIN="$FUNNEL_DOMAIN"
        else
            log_success "Tailscale Funnel started on port ${GUMM_PORT}"
        fi
    else
        log_warn "Failed to start Tailscale Funnel. You can enable it manually:"
        log_info "  tailscale funnel --bg ${GUMM_PORT}"
    fi
}

# =============================================================================
# CONFIGURE VPN MODE IN CONTAINER (via API)
# =============================================================================
# NOTE: VPN daemons run on the HOST, not in the container.
# This function just tells the container which VPN mode is active,
# so the vpn-guard middleware knows to expect traffic via Docker network.
configure_vpn_container() {
    if [[ "$VPN_PROVIDER" == "none" ]]; then
        return 0
    fi

    log_step "Configuring VPN mode ($VPN_PROVIDER) in container..."

    # Wait for Gumm to be ready (up to 60 seconds)
    for i in $(seq 1 30); do
        if curl -sf "http://localhost:${GUMM_PORT}/api/setup/status" &>/dev/null; then
            break
        fi
        sleep 2
    done

    # Login to get a session (use the admin password from config)
    LOGIN_RESPONSE=$(curl -sf -c /tmp/gumm-cookies.txt -X POST \
        "http://localhost:${GUMM_PORT}/api/auth/login" \
        -H "Content-Type: application/json" \
        -d "{\"password\":\"${GUMM_ADMIN_PASSWORD}\"}" 2>/dev/null) || true

    if echo "$LOGIN_RESPONSE" | grep -q '"ok":true'; then
        # Set network mode (just the mode, no auth keys - VPN runs on host)
        if [[ "$VPN_PROVIDER" == "tailscale" ]]; then
            CONNECT_RESPONSE=$(curl -sf -b /tmp/gumm-cookies.txt -X POST \
                "http://localhost:${GUMM_PORT}/api/network/tailscale/connect" \
                -H "Content-Type: application/json" \
                -d "{\"hostname\":\"gumm\"}" 2>/dev/null) || true
        elif [[ "$VPN_PROVIDER" == "netbird" ]]; then
            CONNECT_RESPONSE=$(curl -sf -b /tmp/gumm-cookies.txt -X POST \
                "http://localhost:${GUMM_PORT}/api/network/netbird/connect" \
                -H "Content-Type: application/json" \
                -d "{\"hostname\":\"gumm\"}" 2>/dev/null) || true
        fi

        if echo "$CONNECT_RESPONSE" | grep -q '"ok":true'; then
            log_success "$VPN_PROVIDER mode enabled in container"
        else
            log_warn "Could not set $VPN_PROVIDER mode (configure manually from dashboard)"
        fi

        rm -f /tmp/gumm-cookies.txt
    else
        log_warn "Could not authenticate to API (configure $VPN_PROVIDER from dashboard)"
    fi
}

# =============================================================================
# CONFIGURE TELEGRAM IN CONTAINER (via API)
# =============================================================================
configure_telegram_container() {
    if [[ -z "$TELEGRAM_BOT_TOKEN" ]]; then
        return 0
    fi

    log_step "Configuring Telegram bot in container..."

    # Wait for Gumm to be ready (up to 60 seconds)
    for i in $(seq 1 30); do
        if curl -sf "http://localhost:${GUMM_PORT}/api/setup/status" &>/dev/null; then
            break
        fi
        sleep 2
    done

    # Login to get a session (use the admin password from config)
    LOGIN_RESPONSE=$(curl -sf -c /tmp/gumm-cookies.txt -X POST \
        "http://localhost:${GUMM_PORT}/api/auth/login" \
        -H "Content-Type: application/json" \
        -d "{\"password\":\"${GUMM_ADMIN_PASSWORD}\"}" 2>/dev/null) || true

    if echo "$LOGIN_RESPONSE" | grep -q '"ok":true'; then
        # Setup Telegram bot
        TELEGRAM_RESPONSE=$(curl -sf -b /tmp/gumm-cookies.txt -X POST \
            "http://localhost:${GUMM_PORT}/api/telegram/setup" \
            -H "Content-Type: application/json" \
            -d "{\"botToken\":\"${TELEGRAM_BOT_TOKEN}\",\"allowedChatIds\":\"${TELEGRAM_CHAT_ID:-}\"}" 2>/dev/null) || true

        if echo "$TELEGRAM_RESPONSE" | grep -q '"ok":true\|"configured":true'; then
            log_success "Telegram bot configured"
        else
            log_warn "Could not configure Telegram bot (configure manually from dashboard)"
        fi

        rm -f /tmp/gumm-cookies.txt
    else
        log_warn "Could not authenticate to API (configure Telegram from dashboard)"
    fi
}

# --- INLINED: lib/docker.sh ---

# =============================================================================
# BUILD DOCKER IMAGE
# =============================================================================
build_application() {
    log_step "Building Gumm Docker image..."

    cd "$INSTALL_DIR"

    docker compose build --no-cache

    log_success "Docker image built"
}

# =============================================================================
# START SERVICES
# =============================================================================
start_services() {
    log_step "Starting Gumm services..."

    cd "$INSTALL_DIR"

    # Check for existing volumes
    if docker volume ls -q | grep -q "gumm_gumm-data"; then
        echo ""
        log_warn "Existing Gumm data volume detected."
        echo -e "  ${BOLD}1)${NC} Keep existing data (upgrade / redeploy)"
        echo -e "  ${BOLD}2)${NC} Delete volumes and start fresh"
        echo ""
        read -p "Choose option [1]: " VOLUME_CHOICE </dev/tty
        VOLUME_CHOICE="${VOLUME_CHOICE:-1}"

        if [[ "$VOLUME_CHOICE" == "2" ]]; then
            log_info "Removing existing volumes..."
            docker compose down -v 2>/dev/null || true
            log_success "Volumes removed"
        fi
    fi

    log_info "Starting containers..."
    if [[ "$USE_CADDY_PROXY" == "true" ]]; then
        log_info "Starting with Caddy reverse proxy..."
        # Ensure certs directory exists (required for volume mount)
        mkdir -p /var/lib/tailscale/certs
        docker compose --profile proxy up -d
    else
        docker compose up -d
    fi

    # Wait for services
    log_info "Waiting for services to become healthy..."
    for i in $(seq 1 30); do
        if docker compose exec -T redis redis-cli ping 2>/dev/null | grep -q PONG; then
            break
        fi
        sleep 2
    done

    # Wait for Gumm to respond
    for i in $(seq 1 30); do
        if curl -sf "http://localhost:${GUMM_PORT}/api/setup/status" &>/dev/null; then
            log_success "Gumm is responding"
            break
        fi
        sleep 2
    done

    docker compose ps

    log_success "Services started"
}

# =============================================================================
# RUN DATABASE SEED
# =============================================================================
run_seed() {
    log_step "Seeding database..."

    cd "$INSTALL_DIR"

    # The database is SQLite and gets created automatically on first run.
    # Migrations are applied by Drizzle at build time.
    # The seed script registers the hello-world module.
    if [[ -f "$INSTALL_DIR/modules/user/hello-world/manifest.json" ]]; then
        log_info "Running database seed..."
        docker compose exec -T gumm sh -c "cd /app && bun run scripts/seed.ts" 2>/dev/null && \
            log_success "Seed completed" || \
            log_warn "Seed skipped (will be handled on first launch)"
    else
        log_info "No hello-world module found, skipping seed"
    fi
}

# --- INLINED: lib/service.sh ---

# =============================================================================
# CREATE SYSTEMD SERVICE
# =============================================================================
create_systemd_service() {
    log_step "Creating systemd service..."

    # Build docker compose args based on whether Caddy proxy is enabled
    COMPOSE_PROFILE=""
    if [[ "$USE_CADDY_PROXY" == "true" ]]; then
        COMPOSE_PROFILE="--profile proxy"
    fi

    cat > /etc/systemd/system/gumm.service << EOF
[Unit]
Description=Gumm — Personal AI Assistant
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=$INSTALL_DIR
ExecStart=/bin/bash -c 'docker compose ${COMPOSE_PROFILE} up -d'
ExecStop=/bin/bash -c 'docker compose ${COMPOSE_PROFILE} down'
ExecReload=/bin/bash -c 'docker compose ${COMPOSE_PROFILE} restart'
TimeoutStartSec=0

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable gumm.service

    log_success "Systemd service created and enabled (auto-starts on boot)"
}

# =============================================================================
# PRINT SUMMARY
# =============================================================================
print_summary() {
    # Detect server IP
    SERVER_IP=$(curl -sf https://ifconfig.me 2>/dev/null || hostname -I 2>/dev/null | awk '{print $1}' || echo "<your-server-ip>")

    TAILSCALE_DNS=""
    NETBIRD_IP=""
    if command -v tailscale &> /dev/null && tailscale status &>/dev/null; then
        TAILSCALE_DNS=$(tailscale status --json 2>/dev/null | grep -o '"DNSName":"[^"]*"' | head -1 | sed 's/"DNSName":"//;s/"$//' | sed 's/\.$//')
    fi
    # If Tailscale Funnel was enabled but domain detection failed, use TAILSCALE_DNS
    if [[ "$USE_TAILSCALE_FUNNEL" == "true" ]] && [[ -z "$TAILSCALE_FUNNEL_DOMAIN" ]] && [[ -n "$TAILSCALE_DNS" ]]; then
        TAILSCALE_FUNNEL_DOMAIN="$TAILSCALE_DNS"
    fi
    if command -v netbird &> /dev/null && netbird status 2>/dev/null | grep -q "Connected"; then
        NETBIRD_IP=$(netbird status 2>/dev/null | grep -oP 'IP:\s*\K[0-9.]+' | head -1)
    fi

    echo ""
    echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════════════════════════╗${NC}"
    echo -e "${GREEN}${BOLD}║               Gumm Installation Complete!                      ║${NC}"
    echo -e "${GREEN}${BOLD}║               Installer v${INSTALLER_VERSION}                                    ║${NC}"
    echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${BOLD}Access:${NC}"
    if [[ "$USE_TAILSCALE_FUNNEL" == "true" ]] && [[ -n "$TAILSCALE_FUNNEL_DOMAIN" ]]; then
        echo -e "  Dashboard:    ${GREEN}${BOLD}https://${TAILSCALE_FUNNEL_DOMAIN}${NC}  ${DIM}(via Tailscale Funnel)${NC}"
        echo -e "  ${DIM}Direct:       http://${SERVER_IP}:${GUMM_PORT}${NC}"
    elif [[ "$USE_CADDY_PROXY" == "true" ]] && [[ -n "$CADDY_DOMAIN" ]]; then
        echo -e "  Dashboard:    ${GREEN}${BOLD}https://${CADDY_DOMAIN}${NC}  ${DIM}(via Caddy)${NC}"
        echo -e "  ${DIM}Direct:       http://${SERVER_IP}:${GUMM_PORT}${NC}"
    else
        if [[ -n "$TAILSCALE_DNS" ]]; then
            echo -e "  Dashboard:    ${GREEN}${BOLD}https://${TAILSCALE_DNS}${NC}  ${DIM}(via Tailscale)${NC}"
            echo -e "  ${DIM}Direct:       http://${SERVER_IP}:${GUMM_PORT}${NC}"
        elif [[ -n "$NETBIRD_IP" ]]; then
            echo -e "  Dashboard:    ${CYAN}http://${NETBIRD_IP}:${GUMM_PORT}${NC}  ${DIM}(via NetBird)${NC}"
            echo -e "  ${DIM}Direct:       http://${SERVER_IP}:${GUMM_PORT}${NC}"
        else
            echo -e "  Dashboard:    ${CYAN}http://${SERVER_IP}:${GUMM_PORT}${NC}"
        fi
    fi
    echo ""
    echo -e "${BOLD}First Steps:${NC}"
    echo -e "  1. Open the dashboard URL above"
    echo -e "  2. Complete the ${CYAN}Setup Wizard${NC} at ${CYAN}/setup${NC}"
    echo -e "     → Set your assistant name & personality"
    echo -e "     → Paste your OpenRouter API key"
    echo -e "     → Configure Telegram (optional)"
    echo -e "  3. Start chatting!"
    echo ""
    echo -e "${BOLD}Connect the CLI:${NC}"
    if command -v gumm &>/dev/null; then
        echo -e "  ${GREEN}✓ CLI is installed${NC}"
    else
        echo -e "  ${YELLOW}Install CLI first:${NC}"
        echo -e "  ${CYAN}curl -fsSL https://raw.githubusercontent.com/gumm-ai/gumm/main/scripts/install.sh | bash${NC}"
    fi
    if [[ "$USE_TAILSCALE_FUNNEL" == "true" ]] && [[ -n "$TAILSCALE_FUNNEL_DOMAIN" ]]; then
        echo -e "  ${CYAN}gumm connect https://${TAILSCALE_FUNNEL_DOMAIN}${NC}"
    elif [[ "$USE_CADDY_PROXY" == "true" ]] && [[ -n "$CADDY_DOMAIN" ]]; then
        echo -e "  ${CYAN}gumm connect https://${CADDY_DOMAIN}${NC}"
    elif [[ -n "$TAILSCALE_DNS" ]]; then
        echo -e "  ${CYAN}gumm connect https://${TAILSCALE_DNS}${NC}"
    else
        echo -e "  ${CYAN}gumm connect http://${SERVER_IP}:${GUMM_PORT}${NC}"
    fi
    echo -e "  ${CYAN}gumm login${NC}"
    echo -e "  ${CYAN}gumm chat \"Hello!\"${NC}"
    echo ""
    echo -e "${BOLD}Important Files:${NC}"
    echo -e "  Installation:  ${CYAN}${INSTALL_DIR}${NC}"
    echo -e "  Environment:   ${CYAN}${INSTALL_DIR}/.env${NC}"
    echo -e "  Global config: ${CYAN}/etc/gumm/config${NC}"
    echo -e "  Brain config:  ${CYAN}${INSTALL_DIR}/brain/${NC}"
    echo -e "  User modules:  ${CYAN}${INSTALL_DIR}/modules/user/${NC}"
    echo ""
    echo -e "${BOLD}Useful Commands:${NC}"
    echo -e "  View logs:       ${CYAN}cd ${INSTALL_DIR} && docker compose logs -f${NC}"
    echo -e "  Restart:         ${CYAN}systemctl restart gumm${NC}"
    echo -e "  Stop:            ${CYAN}systemctl stop gumm${NC}"
    echo -e "  Update:          ${CYAN}sudo bash ${INSTALL_DIR}/scripts/update.sh${NC}"
    echo -e "  Uninstall:       ${CYAN}sudo bash ${INSTALL_DIR}/scripts/uninstall.sh${NC}"
    echo -e "  Service status:  ${CYAN}docker compose -f ${INSTALL_DIR}/docker-compose.yml ps${NC}"
    echo ""
    echo -e "${YELLOW}${BOLD}Security Notes:${NC}"
    echo -e "  - The .env file contains your admin password and session secret"
    if [[ "$USE_TAILSCALE_FUNNEL" == "true" ]] && [[ -n "$TAILSCALE_FUNNEL_DOMAIN" ]]; then
        echo -e "  - ${GREEN}✓ Tailscale Funnel is active with HTTPS${NC}"
        echo -e "  - Traffic is routed through Tailscale's edge network"
    elif [[ "$USE_CADDY_PROXY" == "true" ]] && [[ -n "$CADDY_DOMAIN" ]]; then
        echo -e "  - ${GREEN}✓ Caddy reverse proxy is enabled with HTTPS${NC}"
        echo -e "  - VPN Guard will verify your VPN IP for secure access"
    else
        echo -e "  - Consider placing Gumm behind a reverse proxy (Caddy/Nginx) with HTTPS"
        echo -e "  - Or use Tailscale/NetBird for secure private access without exposing ports"
    fi
    echo ""
}


# =============================================================================
# UNINSTALL
# =============================================================================
uninstall() {
    # Delegate to the dedicated uninstall script
    if [[ -f "$SCRIPT_DIR/uninstall.sh" ]]; then
        exec bash "$SCRIPT_DIR/uninstall.sh" "$@"
    elif [[ -f "$INSTALL_DIR/scripts/uninstall.sh" ]]; then
        exec bash "$INSTALL_DIR/scripts/uninstall.sh" "$@"
    else
        log_error "Uninstall script not found"
        log_info "Download and run manually:"
        log_info "  curl -fsSL https://raw.githubusercontent.com/gumm-ai/gumm/main/scripts/uninstall.sh | sudo bash"
        exit 1
    fi
}

# =============================================================================
# MAIN INSTALLATION FLOW
# =============================================================================
main() {
    clear
    echo ""
    echo -e "${GREEN}${BOLD}"
    echo "  ┌────────────────────────────────────────────────────────────┐"
    echo "  │                                                            │"
    echo "  │        ██████╗ ██╗   ██╗███╗   ███╗███╗   ███╗             │"
    echo "  │       ██╔════╝ ██║   ██║████╗ ████║████╗ ████║             │"
    echo "  │       ██║  ███╗██║   ██║██╔████╔██║██╔████╔██║             │"
    echo "  │       ██║   ██║██║   ██║██║╚██╔╝██║██║╚██╔╝██║             │"
    echo "  │       ╚██████╔╝╚██████╔╝██║ ╚═╝ ██║██║ ╚═╝ ██║             │"
    echo "  │        ╚═════╝  ╚═════╝ ╚═╝     ╚═╝╚═╝     ╚═╝             │"
    echo "  │                                                            │"
    echo "  │          VPS Installation Script v${INSTALLER_VERSION}                  │"
    echo "  │                                                            │"
    echo "  └────────────────────────────────────────────────────────────┘"
    echo -e "${NC}"
    echo ""

    preflight_checks
    detect_os
    install_dependencies
    install_go
    install_docker
    
    # Ask user for configuration FIRST (including VPN choice)
    # This way we know which VPN to install before installing any
    prompt_configuration
    
    # Install ONLY the chosen VPN (not both!)
    if [[ "$VPN_PROVIDER" == "tailscale" ]]; then
        install_tailscale
    elif [[ "$VPN_PROVIDER" == "netbird" ]]; then
        install_netbird
    fi
    
    ensure_tun_device
    configure_firewall

    # Determine install source
    # SCRIPT_DIR is already set globally for modules support, but we redefine PARENT_DIR from it
    PARENT_DIR="$(dirname "$SCRIPT_DIR")"

    if [[ -f "$PARENT_DIR/docker-compose.yml" ]] && [[ -f "$PARENT_DIR/Dockerfile" ]]; then
        log_info "Running from existing repository"
        INSTALL_DIR="$PARENT_DIR"
    else
        setup_repository
    fi

    cd "$INSTALL_DIR"

    create_env_file
    build_application
    
    # Start services WITHOUT Caddy first (domain not known yet)
    TEMP_CADDY_PROXY="$USE_CADDY_PROXY"
    USE_CADDY_PROXY="false"
    start_services
    USE_CADDY_PROXY="$TEMP_CADDY_PROXY"
    
    # Now connect VPN on host (so we can detect domain)
    configure_vpn_host
    
    # HTTPS setup: Tailscale Funnel (no Caddy needed) or Caddy reverse proxy
    if [[ "$USE_TAILSCALE_FUNNEL" == "true" ]]; then
        # Tailscale Funnel handles HTTPS natively — no Caddy required
        configure_tailscale_funnel
    else
        # Caddy reverse proxy path (NetBird or manual setup)
        configure_caddy_domain
        configure_caddy_ssl
        
        if [[ "$USE_CADDY_PROXY" == "true" ]] && [[ -n "$CADDY_DOMAIN" ]]; then
            log_info "Restarting with Caddy reverse proxy..."
            mkdir -p /var/lib/tailscale/certs
            docker compose --profile proxy up -d
        fi
    fi
    
    configure_vpn_container
    configure_telegram_container
    run_seed
    install_go
    install_cli
    create_systemd_service
    create_global_config
    print_summary
}

# =============================================================================
# ENTRY POINT
# =============================================================================
case "${1:-}" in
    --uninstall|-u)
        uninstall
        ;;
    --version|-v)
        echo "Gumm Installer v${INSTALLER_VERSION} (${INSTALLER_DATE})"
        exit 0
        ;;
    --help|-h)
        echo "Gumm — VPS Installation Script v${INSTALLER_VERSION}"
        echo ""
        echo "Usage: sudo $0 [options]"
        echo ""
        echo "Options:"
        echo "  --help, -h        Show this help"
        echo "  --version, -v     Show installer version"
        echo "  --uninstall, -u   Remove Gumm and all data"
        echo ""
        echo "Environment Variables (override prompts):"
        echo "  INSTALL_DIR           Installation directory (default: /opt/gumm)"
        echo "  GUMM_ADMIN_PASSWORD   Admin password (prompted if not set)"
        echo "  GUMM_PORT             Web UI port (default: 3000)"
        echo "  REDIS_PORT            Redis port (default: 6379)"
        echo "  VPN_PROVIDER          VPN provider: tailscale, netbird, or none"
        echo "  TAILSCALE_AUTHKEY     Tailscale auth key (optional)"
        echo "  NETBIRD_SETUP_KEY     NetBird setup key (optional)"
        echo "  TELEGRAM_BOT_TOKEN    Telegram bot token (optional)"
        echo "  TELEGRAM_CHAT_ID      Allowed Telegram chat ID (optional)"
        echo "  REPO_URL              Git repository URL"
        echo "  BRANCH                Git branch (default: main)"
        echo ""
        ;;
    *)
        main
        ;;
esac
